# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 298)
        Dialog.setMaximumSize(QtCore.QSize(900, 600))
        Dialog.setStyleSheet("background-color: white")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setMinimumSize(QtCore.QSize(440, 280))
        self.stackedWidget.setStyleSheet("background-color: white;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loadTree = QtWidgets.QWidget()
        self.loadTree.setObjectName("loadTree")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.loadTree)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treesList = QtWidgets.QListWidget(self.loadTree)
        self.treesList.setMinimumSize(QtCore.QSize(0, 0))
        self.treesList.setObjectName("treesList")
        self.horizontalLayout.addWidget(self.treesList)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addTreeButton = QtWidgets.QPushButton(self.loadTree)
        self.addTreeButton.setEnabled(True)
        self.addTreeButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.addTreeButton.setFont(font)
        self.addTreeButton.setStyleSheet("background-color: #85A09A;\n"
"color: white;\n"
"border-radius: 15;")
        self.addTreeButton.setIconSize(QtCore.QSize(28, 28))
        self.addTreeButton.setAutoDefault(False)
        self.addTreeButton.setDefault(False)
        self.addTreeButton.setFlat(True)
        self.addTreeButton.setObjectName("addTreeButton")
        self.verticalLayout_3.addWidget(self.addTreeButton)
        self.importTreeButton = QtWidgets.QPushButton(self.loadTree)
        self.importTreeButton.setEnabled(True)
        self.importTreeButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.importTreeButton.setFont(font)
        self.importTreeButton.setStyleSheet("background-color: #85A09A;\n"
"color: white;\n"
"border-radius: 15;")
        self.importTreeButton.setIconSize(QtCore.QSize(28, 28))
        self.importTreeButton.setAutoDefault(False)
        self.importTreeButton.setDefault(False)
        self.importTreeButton.setFlat(True)
        self.importTreeButton.setObjectName("importTreeButton")
        self.verticalLayout_3.addWidget(self.importTreeButton)
        self.removeTreeButton = QtWidgets.QPushButton(self.loadTree)
        self.removeTreeButton.setEnabled(True)
        self.removeTreeButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.removeTreeButton.setFont(font)
        self.removeTreeButton.setStyleSheet("background-color: #85A09A;\n"
"color: white;\n"
"border-radius: 15;")
        self.removeTreeButton.setIconSize(QtCore.QSize(28, 28))
        self.removeTreeButton.setAutoDefault(False)
        self.removeTreeButton.setDefault(False)
        self.removeTreeButton.setFlat(True)
        self.removeTreeButton.setObjectName("removeTreeButton")
        self.verticalLayout_3.addWidget(self.removeTreeButton)
        self.loadTreeButton = QtWidgets.QPushButton(self.loadTree)
        self.loadTreeButton.setEnabled(True)
        self.loadTreeButton.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.loadTreeButton.setFont(font)
        self.loadTreeButton.setStyleSheet("background-color: #85A09A;\n"
"color: white;\n"
"border-radius: 15;")
        self.loadTreeButton.setIconSize(QtCore.QSize(28, 28))
        self.loadTreeButton.setAutoDefault(False)
        self.loadTreeButton.setDefault(False)
        self.loadTreeButton.setFlat(True)
        self.loadTreeButton.setObjectName("loadTreeButton")
        self.verticalLayout_3.addWidget(self.loadTreeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(self.loadTree)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"color: #85A09A;\n"
"border-style: none;\n"
"text-align: center;\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: #85A09A;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.hide()
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.loadTree)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addTreeButton.setText(_translate("Dialog", "Add New Tree"))
        self.importTreeButton.setText(_translate("Dialog", "Import Tree"))
        self.removeTreeButton.setText(_translate("Dialog", "Remove Tree"))
        self.loadTreeButton.setText(_translate("Dialog", "Load Tree"))
