# Form implementation generated from reading ui file 'EventsListWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(674, 427)
        self.EventsListWidget = QtWidgets.QWidget(Form)
        self.EventsListWidget.setGeometry(QtCore.QRect(30, 20, 500, 131))
        self.EventsListWidget.setMinimumSize(QtCore.QSize(500, 80))
        self.EventsListWidget.setStyleSheet("QWidget{\n"
"background-color: #85A09A;\n"
"border-radius: 20\n"
"}")
        self.EventsListWidget.setObjectName("EventsListWidget")
        self.widget = QtWidgets.QWidget(self.EventsListWidget)
        self.widget.setGeometry(QtCore.QRect(26, 41, 461, 27))
        self.widget.setObjectName("widget")
        self.infoLayout = QtWidgets.QHBoxLayout(self.widget)
        self.infoLayout.setContentsMargins(0, 0, 0, 0)
        self.infoLayout.setObjectName("infoLayout")
        self.eventItemDateLabel = QtWidgets.QLabel(self.widget)
        self.eventItemDateLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.eventItemDateLabel.setFont(font)
        self.eventItemDateLabel.setStyleSheet("color: white")
        self.eventItemDateLabel.setObjectName("eventItemDateLabel")
        self.infoLayout.addWidget(self.eventItemDateLabel)
        self.eventItemPlaceLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.eventItemPlaceLabel.setFont(font)
        self.eventItemPlaceLabel.setStyleSheet("color: white")
        self.eventItemPlaceLabel.setObjectName("eventItemPlaceLabel")
        self.infoLayout.addWidget(self.eventItemPlaceLabel)
        self.eventItemTextLabel = QtWidgets.QLabel(self.EventsListWidget)
        self.eventItemTextLabel.setGeometry(QtCore.QRect(26, 74, 461, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.eventItemTextLabel.setFont(font)
        self.eventItemTextLabel.setStyleSheet("color: white")
        self.eventItemTextLabel.setWordWrap(True)
        self.eventItemTextLabel.setObjectName("eventItemTextLabel")
        self.eventItemTypeLabel = QtWidgets.QLabel(self.EventsListWidget)
        self.eventItemTypeLabel.setGeometry(QtCore.QRect(26, 10, 78, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.eventItemTypeLabel.setFont(font)
        self.eventItemTypeLabel.setStyleSheet("color: white")
        self.eventItemTypeLabel.setObjectName("eventItemTypeLabel")
        self.TwoItemListWidget = QtWidgets.QWidget(Form)
        self.TwoItemListWidget.setGeometry(QtCore.QRect(60, 200, 500, 80))
        self.TwoItemListWidget.setMinimumSize(QtCore.QSize(500, 80))
        self.TwoItemListWidget.setStyleSheet("QWidget{\n"
"background-color: #85A09A;\n"
"border-radius: 20\n"
"}")
        self.TwoItemListWidget.setObjectName("TwoItemListWidget")
        self.twoItemFirst = QtWidgets.QLabel(self.TwoItemListWidget)
        self.twoItemFirst.setGeometry(QtCore.QRect(26, 10, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.twoItemFirst.setFont(font)
        self.twoItemFirst.setStyleSheet("color: white")
        self.twoItemFirst.setObjectName("twoItemFirst")
        self.twoItemSecond = QtWidgets.QLabel(self.TwoItemListWidget)
        self.twoItemSecond.setGeometry(QtCore.QRect(26, 44, 464, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.twoItemSecond.setFont(font)
        self.twoItemSecond.setStyleSheet("color: white")
        self.twoItemSecond.setWordWrap(True)
        self.twoItemSecond.setObjectName("twoItemSecond")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.eventItemDateLabel.setText(_translate("Form", "1 Jan 1900"))
        self.eventItemPlaceLabel.setText(_translate("Form", "Lucknow, United Provinces, India"))
        self.eventItemTextLabel.setText(_translate("Form", "Edward Arthur Henry Blunt woke up in the morning and got out of his bed."))
        self.eventItemTypeLabel.setText(_translate("Form", "Residence"))
        self.twoItemFirst.setText(_translate("Form", "UK Census - 1911"))
        self.twoItemSecond.setText(_translate("Form", "URL: ancestry.com/123456/sources/census-1911"))
